arch: resnet18
n_last_blocks: 4

epochs: 100
pretrained_weights_key: best
checkpoint_key: teacher
lr: 0.001
batch_size_per_gpu: 256
aug_opt: eval
global_crops_size: 224
global_crops_scale:
  - 0.75
  - 1.00
data_path: dataset
num_labels: 2
device: cuda:0
seed: 0
num_workers: 10
weighted_sampler: True
fine_tune: True


# Save file settings ----------------------------------------------------------------------------------------------------
project: runs
name: 20230526_DINO_MixHead
exp_name: best_linear_fine_tune
exist_ok: True