arch: resnet18

momentum_teacher: 0.996

# Head Network settings ------------------------------------------------------------------------------------------------

out_dim: 1024
use_bn_in_head: true
norm_last_layer: true
use_head_prediction: false
use_dense_prediction: false
use_mix_prediction: true

# Augmentation settings ------------------------------------------------------------------------------------------------
data_path: dataset_debug
aug_opt: lymph_node_aug_1
global_crops_size: 224
local_crops_size: 96
global_crops_scale:
  - 0.75
  - 1.00
local_crops_number: 2
local_crops_scale:
  - 0.75
  - 1.00
pretrained_weights_ckpt: ''

# Training settings ----------------------------------------------------------------------------------------------------
warmup_teacher_temp: 0.04
teacher_temp: 0.04
warmup_teacher_temp_epochs: 10

batch_size_per_gpu: 64
min_lr: 1.0e-06
lr: 0.0005
device: cuda:0

amp: true
weight_decay: 0.04
weight_decay_end: 0.4
clip_grad: 3.0
epochs: 10
freeze_last_layer: 1
warmup_epochs: 10
optimizer: adamw
distributed: false
seed: 0
weighted_sampler: false
num_workers: 10


# Save file settings ----------------------------------------------------------------------------------------------------

project: runs
name: debug
exist_ok: True
