arch: resnet18

# Training settings ----------------------------------------------------------------------------------------------------
n_last_blocks: 1
epochs: 5
pretrained_weights_key: best
checkpoint_key: teacher
lr: 0.001
num_labels: 2
batch_size_per_gpu: 32
device: cuda:0
seed: 0
num_workers: 10

# Augmentation settings ------------------------------------------------------------------------------------------------
data_path: dataset_debug
aug_opt: eval
n_splits: 2
global_crops_size: 224
global_crops_scale:
  - 0.75
  - 1.00
weighted_sampler: True
fine_tune: True


# Save file settings ----------------------------------------------------------------------------------------------------
project: debug
name: backbone
exp_name: best_linear_fine_tune
exist_ok: True


# Logging -------------------------------------
wandb: False
