arch: resnet18

# Head Network settings ------------------------------------------------------------------------------------------------
out_dim: 1024
use_bn_in_head: True
norm_last_layer: True
use_head_prediction: False
use_dense_prediction: False
use_mix_prediction: False
use_trans_prediction: False
use_multi_level: True
# Augmentation settings ------------------------------------------------------------------------------------------------
data_path: dataset_debug
aug_opt: lymph_node_aug_1
n_splits: 2
global_crops_size: 224
local_crops_size: 96
global_crops_scale:
  - 0.75
  - 1.00
local_crops_number: 4
local_crops_scale:
  - 0.50
  - 0.75
pretrained_weights_ckpt: ''

# Training settings ----------------------------------------------------------------------------------------------------
momentum_teacher: 0.996
warmup_teacher_temp: 0.04
teacher_temp: 0.04
warmup_teacher_temp_epochs: 10

batch_size_per_gpu: 16
min_lr: 1.0e-06
lr: 5.0e-05
device: cuda:0
amp: true
weight_decay: 0.04
weight_decay_end: 0.4
clip_grad: 3.0
epochs: 10
freeze_last_layer: 1
warmup_epochs: 10
optimizer: sgd
distributed: False
seed: 0
weighted_sampler: True
num_workers: 10


# Save file settings ----------------------------------------------------------------------------------------------------
project: debug
name: backbone
exist_ok: True


# Logging -------------------------------------
wandb: False