# Model settings -------------------------------------------------------------------------------------------------------
arch: swin_t
patch_size: 16
out_dim: 65535
norm_last_layer: True
momentum_teacher: 0.996
use_bn_in_head: False
use_dense_prediction: True

# Temperature teacher parameters ---------------------------------------------------------------------------------------
warmup_teacher_temp: 0.04
teacher_temp: 0.04
warmup_teacher_temp_epochs: 30

# Training/Optimization parameters -------------------------------------------------------------------------------------
use_fp16: True
weight_decay: 0.04
weight_decay_end: 0.4
clip_grad: 3.0
batch: 64
epochs: 500
freeze_last_layer: 1
lr: 0.0005
warmup_epochs: 10
min_lr: 1.0E-6
optimizer: adamw

# Multi-crop parameters ------------------------------------------------------------------------------------------------
aug_opt: lymphNode
global_crops_scale: (0.4,1.0)
local_crops_number: 8
local_crops_scale: (0.05,0.4)
local_crops_size: 96

# Global settings -------------------------------------------------------------------------------------------------------
data_path: "/home/corn/PycharmProjects/LymphNode/dataset"
k_fold: 3
pretrained_weights_ckpt: ""
num_workers: 10
deterministic: False
project: runs
name: debug
exist_ok: True
device: 0
seed: 0
